batch_size: 1
dataset: /home/jvarley/grasp_deep_learning/data/deep_learning_grasp_data/saxena_rgbd_72x72.h5
save_path: /home/jvarley/grasp_deep_learning/pylearn2_classifier_gdl/models/saxena_rgbd_72x72_3_layer_72x72_9_30_13_34
max_epochs: 10000
output_channels_h2: 64
output_channels_h1: 64
output_channels_h0: 64
